///////////////////////////////////////////////////////////
//  Estudiante.java
//  Implementation of the Class Estudiante
//  Generated by Enterprise Architect
//  Created on:      10-feb.-2023 17:16:30
//  Original author: PAVILION
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class Estudiante {

		private String cif;
		private String nombres;
		private String apellidos;
		private DateTime fechaNac;
		private String facultad;
		private String carrera;

        public string Cif { get => cif; set => cif = value; }
        public string Nombres { get => nombres; set => nombres = value; }
        public string Apellidos { get => apellidos; set => apellidos = value; }
        public DateTime FechaNac { get => fechaNac; set => fechaNac = value; }
        public string Facultad { get => facultad; set => facultad = value; }
        public string Carrera { get => carrera; set => carrera = value; }

        public Estudiante(string cif, string nombres, string apellidos, DateTime fechaNac, string facultad, string carrera)
        {
            this.Cif = cif;
            this.Nombres = nombres;
            this.Apellidos = apellidos;
            this.FechaNac = fechaNac;
            this.Facultad = facultad;
            this.Carrera = carrera;
        }

        public Estudiante(){

		}

		~Estudiante(){

		}

	}//end Estudiante

}//end namespace System