///////////////////////////////////////////////////////////
//  Matricula.java
//  Implementation of the Class Matricula
//  Generated by Enterprise Architect
//  Created on:      10-feb.-2023 17:16:30
//  Original author: PAVILION
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Matricula {

		public List<Estudiante> listado = new List<Estudiante>();

		public Matricula(){

		}

        public Matricula(List<Estudiante> listado)
        {
            this.listado = listado;
        }
		public bool agregarISI(Estudiante est)
		{
            if (est.Carrera == "Sistemas")
            {
                listado.Add(est);
                return true;
            }
            return false;
            
		}

	}//end Matricula

}//end namespace System